### Teste GET - listar todos os pontos
GET http://localhost:3000/pontos
Accept: application/json

###

### Teste POST - criar um ponto de doação
POST http://localhost:3000/pontos
Content-Type: application/json

{
  "nome": "SESI/SENAI Ubá",
  "endereco": "Avenida Jesus Brandão",
  "numero": "452",
  "bairro": "San Raphael II",
  "cidade": "Ubá",
  "estado": "MG",
  "cep": "36500-000",
  "itens_recebidos": [
    "Água",
    "Roupas",
    "Alimentos",
    "Colchões",
    "Fraudas"
  ],
  "horario": "08h às 18h",
  "telefone": "(31) 97166-9205"
}

###

### Teste GET - listar novamente para ver se o ponto foi adicionado
GET http://localhost:3000/pontos
Accept: application/json