### Teste GET - listar todos os pontos
GET http://localhost:3000/pontos
Accept: application/json

###

### Teste POST - criar um ponto de doação
POST http://localhost:3000/pontos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVkYjRkMzk0LWY3MmUtNDAxMS1iYWIxLTkzOGE2Yzk5YWVmNyIsImlhdCI6MTc3MjM5NDY1MCwiZXhwIjoxNzcyNDAxODUwfQ.jYF41q7MtgnCfuEKvTWAhX2AEm1LJ5sDCsZATvAg_nw

{
  "nome": "testeteste",
  "endereco": "rua sete lagoas",
  "tipo":"doacao",
  "numero": "140",
  "bairro": "Santana",
  "cidade": "Ubá",
  "estado": "MG",
  "cep": "36500-000",
  "itens_recebidos": [
    "Água",
    "Roupas",
    "Alimentos",
    "Colchões",
    "Fraudas"
  ],
  "horario": "08h às 18h",
  "telefone": "(22) 2222222222"
}

###

### Teste GET - listar novamente para ver se o ponto foi adicionado
GET http://localhost:3000/pontos?tipo=abrigo
Accept: application/json

###

### Teste PATH - Inativar e Ativar ponto de Apoio
PATCH http://localhost:3000/pontos/411d9b2c-10e1-4d20-9e12-fd3679e9ee35/ativo
Accept: application/json